/** Drop tables and database */

DROP TABLE IF EXISTS DietTracker.FOOD CASCADE;
DROP TABLE IF EXISTS DietTracker.PORTIONS CASCADE;
DROP TABLE IF EXISTS DietTracker.MEALS CASCADE;
DROP TABLE IF EXISTS DietTracker.DAYS CASCADE;
DROP TABLE IF EXISTS DietTracker.USERS CASCADE;

/**DROP DATABASE IF EXISTS DietTracker;*/